# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  - package-ecosystem: "composer"
    target-branch: "main"
    directory: "/"
    versioning-strategy: "increase-if-necessary"
    open-pull-requests-limit: 10
    schedule:
        interval: "daily"
    assignees:
        - "pfazzi"
    commit-message:
      include: "scope"
      prefix: "composer"
    labels:
      - "dependency"

