version: "3.5"

services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  nginx:
    platform: linux/x86_64
    build: docker/nginx
    depends_on:
      - app
    environment:
      PHP_FPM_IP: app
      PHP_FPM_PORT: 9000
    ports:
      - 8000:80
    volumes:
      - .:/app
  
  app:
    platform: linux/x86_64
    build:
      context: docker/php
      target: base
    depends_on:
      - mysql
    environment:
      DATABASE_URL: "mysql://app:app@mysql:3306/app?serverVersion=8"
    volumes:
      - .:/app

  admin:
    platform: linux/x86_64
    image: node:12-alpine
    command: sh -c "yarn install && yarn start"
    depends_on:
      - app
    ports:
      - 3000:3000
    volumes:
      - ./admin_frontend:/admin
    working_dir: /admin
